from pathlib import Path
import pandas as pd
from datetime import datetime

PROJECT_ROOT = Path(
    r"C:\Users\Pranoti munjankar\OneDrive\Desktop\DA PROJECTS\Marketlens"
)

CLEANED_DIR = PROJECT_ROOT / "data" / "cleaned"

REPORT_DIR = PROJECT_ROOT / "analysis" / "outputs" / "reports"

REPORT_DIR.mkdir(parents=True, exist_ok=True)

OUTPUT_FILE = REPORT_DIR / "MARKETLENS_DATA_DICTIONARY.txt"

DATASETS = {
    "Global Ads Performance": {
        "file": CLEANED_DIR / "global_ads_performance_cleaned.csv",
        "original_columns": [
            "date",
            "platform",
            "campaign_type",
            "industry",
            "country",
            "impressions",
            "clicks",
            "CTR",
            "CPC",
            "ad_spend",
            "conversions",
            "CPA",
            "revenue",
            "ROAS",
        ],
    },

    "KAG Conversion Data": {
        "file": CLEANED_DIR / "KAG_conversion_data_cleaned.csv",
        "original_columns": [
            "ad_id",
            "xyz_campaign_id",
            "fb_campaign_id",
            "interest",
            "Impressions",
            "Clicks",
            "Spent",
            "Total_Conversion",
            "Approved_Conversion",
            "age",
            "gender",
        ],
    },

    "Marketing A/B Testing": {
        "file": CLEANED_DIR / "marketing_AB_cleaned.csv",
        "original_columns": [
            "Unnamed: 0",
            "user id",
            "test group",
            "converted",
            "total ads",
            "most ads day",
            "most ads hour",
        ],
    },
}

FIELD_INFO = {

    "date": {
        "meaning": "Date on which the advertising activity was recorded.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Time-series analysis, trend analysis and date filtering.",
        "power_bi": "USE - Date field for time analysis and slicers.",
        "notes": "Should be treated as a date rather than text."
    },

    "platform": {
        "meaning": "Advertising platform on which the campaign activity occurred.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Compare advertising efficiency across platforms.",
        "power_bi": "USE - Main segmentation dimension.",
        "notes": "Categorical field."
    },

    "campaign_type": {
        "meaning": "Type or format of advertising campaign.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Compare campaign-format performance.",
        "power_bi": "USE - Campaign segmentation.",
        "notes": "Categorical field."
    },

    "industry": {
        "meaning": "Industry associated with the advertising campaign.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Compare performance across industry segments.",
        "power_bi": "USE - Industry segmentation.",
        "notes": "Categorical field."
    },

    "country": {
        "meaning": "Country associated with the advertising activity.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Geographic performance analysis.",
        "power_bi": "USE - Geographic segmentation and map analysis.",
        "notes": "Categorical geographic field."
    },

    "impressions": {
        "meaning": "Number of times advertisements were displayed.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Measures advertising exposure/reach.",
        "power_bi": "USE - KPI and denominator for CTR.",
        "notes": "Non-negative count."
    },

    "clicks": {
        "meaning": "Number of clicks generated by advertisements.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Measures user engagement with advertisements.",
        "power_bi": "USE - KPI and numerator for CTR.",
        "notes": "Non-negative count."
    },

    "CTR": {
        "meaning": "Reported click-through rate.",
        "role": "Source field",
        "formula": "Reported by source dataset.",
        "business_use": "Measures the percentage of impressions that resulted in clicks.",
        "power_bi": "USE - Performance KPI.",
        "notes": "Validated against calculated CTR."
    },

    "CPC": {
        "meaning": "Reported cost per click.",
        "role": "Source field",
        "formula": "Reported by source dataset.",
        "business_use": "Measures average advertising cost per click.",
        "power_bi": "USE - Efficiency KPI.",
        "notes": "Validated against calculated CPC."
    },

    "ad_spend": {
        "meaning": "Advertising expenditure.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Measures advertising investment.",
        "power_bi": "USE - Cost KPI.",
        "notes": "Monetary field."
    },

    "conversions": {
        "meaning": "Number of conversions attributed to advertising activity.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Measures desired user actions generated by advertising.",
        "power_bi": "USE - Conversion KPI.",
        "notes": "Non-negative count."
    },

    "CPA": {
        "meaning": "Reported cost per acquisition/conversion.",
        "role": "Source field",
        "formula": "Reported by source dataset.",
        "business_use": "Measures acquisition efficiency.",
        "power_bi": "USE - Efficiency KPI.",
        "notes": "Validated against calculated CPA."
    },

    "revenue": {
        "meaning": "Revenue attributed to advertising activity.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Measures financial outcome of advertising.",
        "power_bi": "USE - Revenue KPI.",
        "notes": "Monetary field."
    },

    "ROAS": {
        "meaning": "Reported return on advertising spend.",
        "role": "Source field",
        "formula": "Reported by source dataset.",
        "business_use": "Measures revenue generated relative to advertising spend.",
        "power_bi": "USE - Primary advertising efficiency KPI.",
        "notes": "Validated against calculated ROAS."
    },

    "CTR_Calculated": {
        "meaning": "Click-through rate independently calculated from clicks and impressions.",
        "role": "Derived field",
        "formula": "clicks / impressions",
        "business_use": "Independent KPI validation and analytical CTR calculation.",
        "power_bi": "USE - Prefer for independently calculated KPI measures where appropriate.",
        "notes": "Source CTR is preserved separately."
    },

    "CPC_Calculated": {
        "meaning": "Cost per click independently calculated from advertising spend and clicks.",
        "role": "Derived field",
        "formula": "ad_spend / clicks",
        "business_use": "Independent validation of reported CPC.",
        "power_bi": "USE - KPI validation/reference.",
        "notes": "Returns missing value where clicks are zero."
    },

    "CPA_Calculated": {
        "meaning": "Cost per acquisition independently calculated from advertising spend and conversions.",
        "role": "Derived field",
        "formula": "ad_spend / conversions",
        "business_use": "Independent validation of reported CPA.",
        "power_bi": "USE - KPI validation/reference.",
        "notes": "Returns missing value where conversions are zero."
    },

    "ROAS_Calculated": {
        "meaning": "Return on advertising spend independently calculated from revenue and advertising spend.",
        "role": "Derived field",
        "formula": "revenue / ad_spend",
        "business_use": "Independent validation of reported ROAS.",
        "power_bi": "USE - KPI calculation/reference.",
        "notes": "Returns missing value where advertising spend is zero."
    },

    "CTR_Validation_Difference": {
        "meaning": "Absolute difference between reported CTR and calculated CTR.",
        "role": "Derived validation field",
        "formula": "ABS(CTR - CTR_Calculated)",
        "business_use": "Measures consistency between reported and calculated CTR.",
        "power_bi": "FLAG / QA - Usually hidden from executive dashboard.",
        "notes": "Used for data-quality validation."
    },

    "CPC_Validation_Difference": {
        "meaning": "Absolute difference between reported CPC and calculated CPC.",
        "role": "Derived validation field",
        "formula": "ABS(CPC - CPC_Calculated)",
        "business_use": "Measures consistency between reported and calculated CPC.",
        "power_bi": "FLAG / QA - Usually hidden from executive dashboard.",
        "notes": "Used for data-quality validation."
    },

    "CPA_Validation_Difference": {
        "meaning": "Absolute difference between reported CPA and calculated CPA.",
        "role": "Derived validation field",
        "formula": "ABS(CPA - CPA_Calculated)",
        "business_use": "Measures consistency between reported and calculated CPA.",
        "power_bi": "FLAG / QA - Usually hidden from executive dashboard.",
        "notes": "Used for data-quality validation."
    },

    "ROAS_Validation_Difference": {
        "meaning": "Absolute difference between reported ROAS and calculated ROAS.",
        "role": "Derived validation field",
        "formula": "ABS(ROAS - ROAS_Calculated)",
        "business_use": "Measures consistency between reported and calculated ROAS.",
        "power_bi": "FLAG / QA - Usually hidden from executive dashboard.",
        "notes": "Used for data-quality validation."
    },

    "CTR_%": {
        "meaning": "CTR represented as a percentage for business reporting.",
        "role": "Derived field",
        "formula": "(clicks / impressions) × 100",
        "business_use": "Dashboard-friendly CTR presentation.",
        "power_bi": "USE - KPI display.",
        "notes": "Formatted as percentage in Power BI."
    },

    "CTR_Validation_Flag": {
        "meaning": "Indicates whether reported CTR is within the validation tolerance.",
        "role": "Derived validation field",
        "formula": "Validation difference compared with predefined tolerance.",
        "business_use": "KPI quality assurance.",
        "power_bi": "QA ONLY - Optional quality indicator.",
        "notes": "Not a performance KPI."
    },

    "CPC_Validation_Flag": {
        "meaning": "Indicates whether reported CPC is within the validation tolerance.",
        "role": "Derived validation field",
        "formula": "Validation difference compared with predefined tolerance.",
        "business_use": "KPI quality assurance.",
        "power_bi": "QA ONLY - Optional quality indicator.",
        "notes": "Not a performance KPI."
    },

    "CPA_Validation_Flag": {
        "meaning": "Indicates whether reported CPA is within the validation tolerance.",
        "role": "Derived validation field",
        "formula": "Validation difference compared with predefined tolerance.",
        "business_use": "KPI quality assurance.",
        "power_bi": "QA ONLY - Optional quality indicator.",
        "notes": "Not a performance KPI."
    },

    "ROAS_Validation_Flag": {
        "meaning": "Indicates whether reported ROAS is within the validation tolerance.",
        "role": "Derived validation field",
        "formula": "Validation difference compared with predefined tolerance.",
        "business_use": "KPI quality assurance.",
        "power_bi": "QA ONLY - Optional quality indicator.",
        "notes": "Not a performance KPI."
    },

    "ad_id": {
        "meaning": "Identifier for the advertisement record.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Record-level identification and traceability.",
        "power_bi": "METADATA - Use for detail-level analysis only.",
        "notes": "Identifier, not a performance measure."
    },

    "xyz_campaign_id": {
        "meaning": "Campaign identifier used in the source dataset.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Campaign-level segmentation.",
        "power_bi": "USE - Campaign analysis.",
        "notes": "Identifier/categorical field."
    },

    "fb_campaign_id": {
        "meaning": "Facebook campaign identifier from the source dataset.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Campaign traceability and segmentation.",
        "power_bi": "USE - Campaign identification.",
        "notes": "Identifier, not continuous numeric data."
    },

    "interest": {
        "meaning": "Interest category/code associated with the advertisement.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Audience-interest segmentation.",
        "power_bi": "USE - Segment analysis.",
        "notes": "Numeric-coded categorical variable; do not treat as continuous."
    },

    "Impressions": {
        "meaning": "Number of advertisement impressions.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Measures advertising exposure.",
        "power_bi": "USE - Exposure KPI.",
        "notes": "Non-negative count."
    },

    "Clicks": {
        "meaning": "Number of clicks generated by the advertisement.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Measures engagement.",
        "power_bi": "USE - Engagement KPI.",
        "notes": "Non-negative count."
    },

    "Spent": {
        "meaning": "Amount spent on the advertisement.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Measures advertising investment.",
        "power_bi": "USE - Cost KPI.",
        "notes": "Monetary field."
    },

    "Total_Conversion": {
        "meaning": "Total conversion count reported at advertisement-record level.",
        "role": "Source field",
        "formula": "Reported by source dataset.",
        "business_use": "Measures reported conversion activity.",
        "power_bi": "USE - Conversion analysis.",
        "notes": "The dataset contains 218 records where Total_Conversion > Clicks; this is retained as a source-definition/data-quality flag rather than automatically corrected."
    },

    "Approved_Conversion": {
        "meaning": "Number of approved conversions reported by the source.",
        "role": "Source field",
        "formula": "Reported by source dataset.",
        "business_use": "Measures approved conversion outcomes.",
        "power_bi": "USE - Primary conversion-quality KPI.",
        "notes": "Should not exceed Total_Conversion."
    },

    "age": {
        "meaning": "Age-group segment associated with the advertisement audience.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Age-based audience segmentation.",
        "power_bi": "USE - Audience segmentation.",
        "notes": "Categorical field."
    },

    "gender": {
        "meaning": "Gender segment associated with the advertisement audience.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Gender-based audience segmentation.",
        "power_bi": "USE - Audience segmentation.",
        "notes": "Categorical field."
    },

    "Click_to_Total_Conversion_%": {
        "meaning": "Percentage of clicks associated with total conversions.",
        "role": "Derived field",
        "formula": "(Total_Conversion / Clicks) × 100",
        "business_use": "Conversion efficiency analysis.",
        "power_bi": "USE - Funnel KPI.",
        "notes": "Undefined when clicks are zero; retained as blank."
    },

    "Click_to_Approved_Conversion_%": {
        "meaning": "Percentage of clicks associated with approved conversions.",
        "role": "Derived field",
        "formula": "(Approved_Conversion / Clicks) × 100",
        "business_use": "Approved conversion efficiency.",
        "power_bi": "USE - Funnel KPI.",
        "notes": "Undefined when clicks are zero; retained as blank."
    },

    "Total_to_Approved_Conversion_%": {
        "meaning": "Percentage of total conversions that are approved conversions.",
        "role": "Derived field",
        "formula": "(Approved_Conversion / Total_Conversion) × 100",
        "business_use": "Measures conversion approval quality.",
        "power_bi": "USE - Conversion-quality KPI.",
        "notes": "Undefined when Total_Conversion is zero."
    },

    "CPC": {
        "meaning": "Cost per click calculated from advertising spend and clicks.",
        "role": "Derived field",
        "formula": "Spent / Clicks",
        "business_use": "Measures click acquisition cost.",
        "power_bi": "USE - Efficiency KPI.",
        "notes": "Undefined when clicks are zero."
    },

    "Cost_per_Approved_Conversion": {
        "meaning": "Advertising cost required per approved conversion.",
        "role": "Derived field",
        "formula": "Spent / Approved_Conversion",
        "business_use": "Measures approved-conversion acquisition efficiency.",
        "power_bi": "USE - Efficiency KPI.",
        "notes": "Undefined when approved conversions are zero."
    },

    "Total_Conversion_Greater_Than_Clicks_Flag": {
        "meaning": "Flags records where reported total conversions exceed reported clicks.",
        "role": "Derived quality flag",
        "formula": "Total_Conversion > Clicks",
        "business_use": "Identifies records requiring source-definition interpretation.",
        "power_bi": "QA ONLY - Use for data-quality monitoring.",
        "notes": "Do not automatically delete these records."
    },

    "Approved_Greater_Than_Total_Flag": {
        "meaning": "Flags records where approved conversions exceed total conversions.",
        "role": "Derived quality flag",
        "formula": "Approved_Conversion > Total_Conversion",
        "business_use": "Logical consistency check.",
        "power_bi": "QA ONLY.",
        "notes": "Expected value is zero."
    },

    "Negative_Value_Flag": {
        "meaning": "Flags records containing negative numeric values.",
        "role": "Derived quality flag",
        "formula": "Any monitored numeric metric < 0",
        "business_use": "Detects invalid negative measurements.",
        "power_bi": "QA ONLY.",
        "notes": "Expected value is zero."
    },

    "Unnamed: 0": {
        "meaning": "Index-like metadata column retained from the source dataset.",
        "role": "Source metadata",
        "formula": "Not applicable",
        "business_use": "Source traceability only.",
        "power_bi": "DO NOT USE - Metadata only.",
        "notes": "Do not use as an analytical feature, KPI, grouping field or relationship key."
    },

    "user id": {
        "meaning": "Unique identifier for an individual user.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "User-level identification and experiment analysis.",
        "power_bi": "METADATA - Useful for distinct-user counting.",
        "notes": "Do not sum this field."
    },

    "test group": {
        "meaning": "Experiment group assigned to the user: advertising group or public-service-announcement control group.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Primary A/B test segmentation variable.",
        "power_bi": "USE - Main experiment dimension.",
        "notes": "Categorical field."
    },

    "converted": {
        "meaning": "Indicates whether the user converted.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Primary experiment outcome variable.",
        "power_bi": "USE - Conversion KPI.",
        "notes": "Boolean outcome."
    },

    "total ads": {
        "meaning": "Total number of advertisements shown to the user.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Measures advertising exposure.",
        "power_bi": "USE - Exposure analysis.",
        "notes": "Highly right-skewed exposure variable; IQR outliers are flagged, not deleted."
    },

    "most ads day": {
        "meaning": "Day of the week on which the user received the highest number of advertisements.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Day-of-week exposure analysis.",
        "power_bi": "USE - Time-based segmentation.",
        "notes": "Categorical time field."
    },

    "most ads hour": {
        "meaning": "Hour of the day during which the user received the highest number of advertisements.",
        "role": "Source field",
        "formula": "Not applicable",
        "business_use": "Hourly advertising exposure analysis.",
        "power_bi": "USE - Time-of-day analysis.",
        "notes": "Treat as a categorical/time dimension."
    },

    "Index_Metadata_Flag": {
        "meaning": "Indicates that the original index-like column is metadata rather than an analytical variable.",
        "role": "Derived quality/metadata flag",
        "formula": "Based on source index structure.",
        "business_use": "Documents source metadata.",
        "power_bi": "DO NOT USE - Documentation only.",
        "notes": "Supports transparency of the cleaned dataset."
    },

    "Negative_Total_Ads_Flag": {
        "meaning": "Flags users with a negative total advertisement exposure count.",
        "role": "Derived quality flag",
        "formula": "total ads < 0",
        "business_use": "Logical data-quality validation.",
        "power_bi": "QA ONLY.",
        "notes": "Expected value is zero."
    },

    "Invalid_Conversion_Value_Flag": {
        "meaning": "Flags conversion values outside the expected binary outcome.",
        "role": "Derived quality flag",
        "formula": "converted not in {False, True}",
        "business_use": "Experiment outcome validation.",
        "power_bi": "QA ONLY.",
        "notes": "Expected value is zero."
    },

    "Ad_Exposure_Level": {
        "meaning": "Categorical classification of user advertising exposure.",
        "role": "Derived segmentation field",
        "formula": "Exposure bands derived from total ads.",
        "business_use": "Compare conversion behaviour across exposure levels.",
        "power_bi": "USE - Exposure segmentation.",
        "notes": "Useful for descriptive analysis; does not by itself establish causality."
    },

    "total ads_IQR_Outlier_Flag": {
        "meaning": "Flags unusually high or low advertisement exposure using the IQR rule.",
        "role": "Derived quality flag",
        "formula": "Value outside Q1 - 1.5×IQR or Q3 + 1.5×IQR",
        "business_use": "Outlier identification.",
        "power_bi": "QA / optional analysis.",
        "notes": "Outliers are flagged rather than removed."
    },

    "Duplicate_User_ID_Flag": {
        "meaning": "Flags repeated user identifiers.",
        "role": "Derived quality flag",
        "formula": "User ID appears more than once.",
        "business_use": "Experiment-level uniqueness validation.",
        "power_bi": "QA ONLY.",
        "notes": "Current cleaned dataset contains no duplicate user IDs."
    },

    "Missing_Value_Flag": {
        "meaning": "Indicates whether a record contains missing values.",
        "role": "Derived quality flag",
        "formula": "One or more fields are missing.",
        "business_use": "Data-quality monitoring.",
        "power_bi": "QA ONLY.",
        "notes": "Current Marketing A/B dataset contains no missing values."
    },

    "Data_Quality_Flag": {
        "meaning": "Combined indicator for selected data-quality issues.",
        "role": "Derived quality flag",
        "formula": "Combination of relevant quality checks.",
        "business_use": "Overall record-level data-quality monitoring.",
        "power_bi": "QA ONLY.",
        "notes": "Not a business performance metric."
    },
}


def infer_field_info(column_name, dtype):
    """
    Provides a fallback description for fields not explicitly
    documented in FIELD_INFO.
    """

    lower_name = column_name.lower()

    if "flag" in lower_name:
        return {
            "meaning": "Derived data-quality or validation indicator.",
            "role": "Derived quality flag",
            "formula": "See cleaning/validation logic.",
            "business_use": "Data-quality monitoring.",
            "power_bi": "QA ONLY.",
            "notes": "Derived automatically during cleaning."
        }

    if "calculated" in lower_name:
        return {
            "meaning": "Independently calculated analytical metric.",
            "role": "Derived field",
            "formula": "Calculated from source fields.",
            "business_use": "KPI calculation and validation.",
            "power_bi": "USE - Analytical/reference KPI.",
            "notes": "Derived during cleaning."
        }

    if "validation" in lower_name:
        return {
            "meaning": "KPI validation field.",
            "role": "Derived validation field",
            "formula": "Comparison between reported and calculated values.",
            "business_use": "Data-quality validation.",
            "power_bi": "QA ONLY.",
            "notes": "Derived during cleaning."
        }

    if "outlier" in lower_name:
        return {
            "meaning": "Indicator identifying an IQR-based statistical outlier.",
            "role": "Derived quality flag",
            "formula": "IQR rule: below Q1 - 1.5×IQR or above Q3 + 1.5×IQR.",
            "business_use": "Outlier identification and investigation.",
            "power_bi": "QA / optional analysis.",
            "notes": "Outliers are flagged, not deleted."
        }

    if "date" in lower_name:
        return {
            "meaning": "Date/time field associated with the record.",
            "role": "Source or derived field",
            "formula": "Not applicable",
            "business_use": "Time-based analysis.",
            "power_bi": "USE - Date/time analysis.",
            "notes": "Use appropriate date/time data type."
        }

    if "id" in lower_name:
        return {
            "meaning": "Identifier used to distinguish records or entities.",
            "role": "Source field",
            "formula": "Not applicable",
            "business_use": "Traceability and distinct counting.",
            "power_bi": "METADATA / USE FOR DISTINCT COUNT.",
            "notes": "Do not treat as a continuous measure."
        }

    if pd.api.types.is_numeric_dtype(dtype):
        return {
            "meaning": "Numeric analytical field.",
            "role": "Source or derived field",
            "formula": "Not applicable",
            "business_use": "Quantitative analysis and KPI calculation.",
            "power_bi": "USE - Subject to business meaning.",
            "notes": "Review aggregation behaviour before dashboard use."
        }

    return {
        "meaning": "Categorical or textual field.",
        "role": "Source or derived field",
        "formula": "Not applicable",
        "business_use": "Segmentation, filtering or descriptive analysis.",
        "power_bi": "USE - Dimension/filter where appropriate.",
        "notes": "Categorical/text field."
    }


def classify_column(column_name, original_columns):

    if column_name in original_columns:
        if column_name == "Unnamed: 0":
            return "Source metadata"

        return "Source field"

    return "Derived field"


def format_value(value):

    if pd.isna(value):
        return "NA"

    if isinstance(value, float):
        return f"{value:.4f}"

    return str(value)


def build_dataset_section(dataset_name, config):

    file_path = config["file"]
    original_columns = config["original_columns"]

    lines = []

    lines.append("=" * 100)
    lines.append(f"DATASET: {dataset_name}")
    lines.append("=" * 100)
    lines.append("")

    lines.append(f"File: {file_path}")
    lines.append("")

    if not file_path.exists():

        lines.append("STATUS: FILE NOT FOUND")
        lines.append("")
        lines.append(
            "Please verify that the cleaned CSV exists in data/cleaned."
        )

        return lines

    df = pd.read_csv(file_path)

    lines.append("DATASET OVERVIEW")
    lines.append("-" * 100)

    lines.append(f"Rows: {len(df):,}")
    lines.append(f"Columns: {len(df.columns):,}")
    lines.append(f"Source columns: {len(original_columns):,}")
    lines.append(
        f"Derived / analytical columns: "
        f"{len([c for c in df.columns if c not in original_columns]):,}"
    )

    lines.append("")

    lines.append(
        f"Total missing cells: {int(df.isna().sum().sum()):,}"
    )

    lines.append(
        f"Duplicate rows: {int(df.duplicated().sum()):,}"
    )

    lines.append("")

    lines.append("COLUMN INVENTORY")
    lines.append("-" * 100)

    lines.append(
        "No. | Field Name | Origin | Data Type | Non-Null | "
        "Missing | Unique"
    )

    lines.append("-" * 100)

    for index, column in enumerate(df.columns, start=1):

        origin = classify_column(column, original_columns)

        dtype = str(df[column].dtype)

        non_null = int(df[column].notna().sum())

        missing = int(df[column].isna().sum())

        unique = int(df[column].nunique(dropna=True))

        lines.append(
            f"{index:>3} | "
            f"{column:<42} | "
            f"{origin:<22} | "
            f"{dtype:<12} | "
            f"{non_null:>8,} | "
            f"{missing:>7,} | "
            f"{unique:>7,}"
        )

    lines.append("")

    lines.append("DETAILED FIELD DEFINITIONS")
    lines.append("-" * 100)

    for index, column in enumerate(df.columns, start=1):

        origin = classify_column(column, original_columns)

        if column in FIELD_INFO:
            info = FIELD_INFO[column]
        else:
            info = infer_field_info(column, df[column].dtype)

        lines.append("")
        lines.append(f"{index}. {column}")
        lines.append("~" * 100)

        lines.append(f"Origin / Role: {origin}")

        lines.append(
            f"Data Type: {df[column].dtype}"
        )

        lines.append(
            f"Non-Null Values: {int(df[column].notna().sum()):,}"
        )

        lines.append(
            f"Missing Values: {int(df[column].isna().sum()):,}"
        )

        lines.append(
            f"Unique Values: {int(df[column].nunique(dropna=True)):,}"
        )

        lines.append(
            f"Meaning: {info['meaning']}"
        )

        lines.append(
            f"Formula / Definition: {info['formula']}"
        )

        lines.append(
            f"Business / Analytical Use: {info['business_use']}"
        )

        lines.append(
            f"Power BI Recommendation: {info['power_bi']}"
        )

        lines.append(
            f"Notes: {info['notes']}"
        )

    lines.append("")

    numeric_columns = df.select_dtypes(
        include="number"
    ).columns.tolist()

    if numeric_columns:

        lines.append("NUMERIC FIELD SUMMARY")
        lines.append("-" * 100)

        lines.append(
            "Field | Minimum | Maximum | Mean | Median"
        )

        lines.append("-" * 100)

        for column in numeric_columns:

            series = pd.to_numeric(
                df[column],
                errors="coerce"
            ).dropna()

            if len(series) == 0:
                continue

            lines.append(
                f"{column:<42} | "
                f"{series.min():>12.4f} | "
                f"{series.max():>12.4f} | "
                f"{series.mean():>12.4f} | "
                f"{series.median():>12.4f}"
            )

        lines.append("")

    categorical_columns = df.select_dtypes(
        include=["object", "category", "bool"]
    ).columns.tolist()

    if categorical_columns:

        lines.append("CATEGORICAL FIELD SUMMARY")
        lines.append("-" * 100)

        for column in categorical_columns:

            unique_values = (
                df[column]
                .dropna()
                .astype(str)
                .unique()
                .tolist()
            )
             
            if len(unique_values) <= 30:

                values = ", ".join(
                    sorted(unique_values)
                )

            else:

                values = (
                    f"{len(unique_values):,} unique values "
                    f"(full list omitted)"
                )

            lines.append(
                f"{column}: {values}"
            )

        lines.append("")

    lines.append("DATASET-SPECIFIC ANALYTICAL NOTES")
    lines.append("-" * 100)

    if dataset_name == "Global Ads Performance":

        lines.append(
            "1. Reported CTR, CPC, CPA and ROAS are preserved from the source."
        )

        lines.append(
            "2. Independently calculated KPI fields are retained for validation."
        )

        lines.append(
            "3. IQR outlier flags are retained for investigation; no observations "
            "were automatically removed."
        )

        lines.append(
            "4. CTR should be interpreted consistently: the source CTR is a ratio, "
            "while CTR_% is the percentage representation."
        )

        lines.append(
            "5. For aggregated Power BI reporting, calculate CTR from total clicks "
            "divided by total impressions rather than averaging row-level CTR."
        )

    elif dataset_name == "KAG Conversion Data":

        lines.append(
            "1. Interest is a numeric-coded categorical variable and should not "
            "be interpreted as a continuous measurement."
        )

        lines.append(
            "2. The cleaned dataset retains records where Total_Conversion "
            "exceeds Clicks."
        )

        lines.append(
            "3. This conversion anomaly is documented and flagged rather than "
            "automatically corrected because the source dataset's metric "
            "definition is not independently established."
        )

        lines.append(
            "4. Ratio fields may contain analytical NaN values where the "
            "denominator is zero. These are not missing source observations."
        )

        lines.append(
            "5. For Power BI, calculate aggregate conversion rates from aggregated "
            "numerators and denominators rather than averaging row-level rates."
        )

    elif dataset_name == "Marketing A/B Testing":

        lines.append(
            "1. 'Unnamed: 0' is retained for source traceability but should not "
            "be used as an analytical feature."
        )

        lines.append(
            "2. 'user id' is an identifier and should be counted distinctly."
        )

        lines.append(
            "3. 'test group' is the primary A/B experiment dimension."
        )

        lines.append(
            "4. 'converted' is the primary experiment outcome."
        )

        lines.append(
            "5. High-exposure users identified through the IQR rule are flagged "
            "but not deleted."
        )

        lines.append(
            "6. Statistical significance should not automatically be interpreted "
            "as causal proof without considering experimental design and other "
            "possible sources of bias."
        )

    lines.append("")

    return lines


def build_power_bi_guidance():

    lines = []

    lines.append("=" * 100)
    lines.append("POWER BI DATA MODELING GUIDANCE")
    lines.append("=" * 100)
    lines.append("")

    lines.append(
        "The cleaned datasets are prepared for dashboard development."
    )

    lines.append("")

    lines.append("Recommended treatment of fields:")
    lines.append("")

    lines.append(
        "USE:"
    )
    lines.append(
        "• Business dimensions such as platform, campaign type, industry, "
        "country, age, gender, test group and exposure level."
    )
    lines.append(
        "• Core metrics such as impressions, clicks, spend, conversions, "
        "revenue and approved conversions."
    )
    lines.append(
        "• Derived KPI fields where they represent meaningful business metrics."
    )

    lines.append("")

    lines.append(
        "CALCULATE IN POWER BI WHEN POSSIBLE:"
    )
    lines.append(
        "• CTR = Total Clicks / Total Impressions"
    )
    lines.append(
        "• CPC = Total Spend / Total Clicks"
    )
    lines.append(
        "• CPA = Total Spend / Total Conversions"
    )
    lines.append(
        "• ROAS = Total Revenue / Total Spend"
    )

    lines.append("")

    lines.append(
        "WHY:"
    )
    lines.append(
        "Aggregated ratios should generally be calculated from aggregated "
        "numerators and denominators rather than averaged from row-level ratios."
    )

    lines.append("")

    lines.append(
        "QA / HIDDEN FROM MAIN DASHBOARD:"
    )
    lines.append(
        "• Validation difference fields"
    )
    lines.append(
        "• Validation flags"
    )
    lines.append(
        "• IQR outlier flags"
    )
    lines.append(
        "• Negative-value flags"
    )
    lines.append(
        "• Duplicate flags"
    )
    lines.append(
        "• Missing-value flags"
    )

    lines.append("")

    lines.append(
        "DO NOT USE AS ANALYTICAL FEATURES:"
    )
    lines.append(
        "• Marketing A/B 'Unnamed: 0' index metadata"
    )

    lines.append("")

    lines.append(
        "IDENTIFIER FIELDS:"
    )
    lines.append(
        "Use IDs for traceability or DISTINCTCOUNT where appropriate; "
        "do not sum identifier values."
    )

    lines.append("")

    return lines


def build_quality_section():

    lines = []

    lines.append("=" * 100)
    lines.append("DATA QUALITY AND CLEANING PRINCIPLES")
    lines.append("=" * 100)
    lines.append("")

    lines.append(
        "1. RAW DATA PRESERVATION"
    )
    lines.append(
        "The original CSV files in data/raw are preserved unchanged."
    )

    lines.append("")

    lines.append(
        "2. CLEANED DATA LAYER"
    )
    lines.append(
        "The data/cleaned directory contains one cleaned dataset per source "
        "dataset. Analytical and quality fields were added without deleting "
        "the original source columns."
    )

    lines.append("")

    lines.append(
        "3. OUTLIER HANDLING"
    )
    lines.append(
        "Outliers are identified using the IQR rule and flagged for investigation. "
        "They are not automatically removed because statistical unusualness does "
        "not necessarily indicate invalid data."
    )

    lines.append("")

    lines.append(
        "4. KPI VALIDATION"
    )
    lines.append(
        "Reported advertising KPIs are independently recalculated where "
        "mathematically possible. Validation differences and flags are retained "
        "for transparency."
    )

    lines.append("")

    lines.append(
        "5. DIVISION-BY-ZERO HANDLING"
    )
    lines.append(
        "Calculated ratios with a zero denominator are represented as missing "
        "analytical values rather than being incorrectly forced to zero."
    )

    lines.append("")

    lines.append(
        "6. SOURCE-DEFINITION ANOMALIES"
    )
    lines.append(
        "The KAG dataset contains records where Total_Conversion exceeds Clicks. "
        "These records are retained and explicitly flagged because the exact "
        "source metric definition is not independently established."
    )

    lines.append("")

    lines.append(
        "7. TRACEABILITY"
    )
    lines.append(
        "Source fields are retained in the cleaned datasets so that calculated "
        "metrics and analytical transformations can be traced back to the "
        "original observations."
    )

    lines.append("")

    return lines


def main():

    report_lines = []

    report_lines.append("=" * 100)
    report_lines.append("MARKETLENS DATA DICTIONARY")
    report_lines.append("=" * 100)
    report_lines.append("")

    report_lines.append(
        "Purpose: Comprehensive documentation of the cleaned datasets "
        "prepared for MarketLens analytics and Power BI dashboard development."
    )

    report_lines.append("")

    report_lines.append(
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )

    report_lines.append("")

    report_lines.append(
        f"Project Root: {PROJECT_ROOT}"
    )

    report_lines.append("")

    report_lines.append(
        f"Cleaned Data Directory: {CLEANED_DIR}"
    )

    report_lines.append("")

    report_lines.append(
        "Important: This report documents the cleaned data layer. "
        "It does not modify any CSV files."
    )

    report_lines.append("")

    for dataset_name, config in DATASETS.items():

        section = build_dataset_section(
            dataset_name,
            config
        )

        report_lines.extend(section)

    report_lines.extend(
        build_power_bi_guidance()
    )

    report_lines.extend(
        build_quality_section()
    )

    report_lines.append("=" * 100)
    report_lines.append("END OF MARKETLENS DATA DICTIONARY")
    report_lines.append("=" * 100)
    report_lines.append("")

    with open(
        OUTPUT_FILE,
        "w",
        encoding="utf-8"
    ) as file:

        file.write(
            "\n".join(report_lines)
        )

    print("=" * 80)
    print("MARKETLENS DATA DICTIONARY GENERATED SUCCESSFULLY")
    print("=" * 80)
    print()
    print(f"Output file:")
    print(OUTPUT_FILE)
    print()
    print("Datasets documented:")

    for dataset_name, config in DATASETS.items():

        if config["file"].exists():

            df = pd.read_csv(
                config["file"],
                nrows=5
            )

            print(
                f"  ✓ {dataset_name}: "
                f"{len(df.columns)} columns inspected"
            )

        else:

            print(
                f"  ✗ {dataset_name}: FILE NOT FOUND"
            )

    print()
    print("No CSV files were modified.")
    print("=" * 80)


if __name__ == "__main__":
    main()
